sudo: required
language: java

services:
    - docker

before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce

script:
    # before test
    - docker build -t ceron-analyze-dev -f Dockerfile-dev .
    - docker run -d --name s3 -e "MINIO_ACCESS_KEY=s3_access" -e "MINIO_SECRET_KEY=s3_secret" minio/minio server /export
    - docker run --rm --link "s3:s3" -e "AWS_ACCESS_KEY_ID=s3_access" -e "AWS_SECRET_ACCESS_KEY=s3_secret" -e "AWS_DEFAULT_REGION=us-east-1" garland/aws-cli-docker aws --endpoint-url http://s3:9000 s3 mb s3://ceron
    # testing
    - docker run --name ceron-analyze-dev --rm --link "s3:s3" -v "${HOME}/.m2:/root/.m2" -v "$(pwd):/var/my-app" -e "S3_URL=http://s3:9000/" -e "S3_BUCKET=ceron" -e "S3_ACCESS_ID=s3_access" -e "S3_SECRET_KEY=s3_secret" ceron-analyze-dev
    # after test
    - docker build -t u6kapps/ceron-analyze .

after_success:
    - if [ -n "$TRAVIS_TAG" ]; then
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
          docker tag u6kapps/ceron-analyze u6kapps/ceron-analyze:$TRAVIS_TAG;
          docker push u6kapps/ceron-analyze;
      else
          echo skip docker push;
      fi
