s3:
  region: <%= ENV["S3_REGION"] %>
  access_key: <%= ENV["S3_ACCESS_KEY"] %>
  secret_key: <%= ENV["S3_SECRET_KEY"] %>
  endpoint: <%= ENV["S3_ENDPOINT"] %>
  bucket: <%= ENV["S3_BUCKET"] %>
  folder: <%= ENV["S3_FOLDER"] %>
  force_path_style: true
